<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<AssemblyName>buildcli</AssemblyName>
		<RootNamespace>Ingenium.BuildCli</RootNamespace>
		<Description>CLI for adding and updating the Ingenium Build git submodule.</Description>
		<PackAsTool>true</PackAsTool>
		<ToolCommandName>buildcli</ToolCommandName>
		<PackageId>Ingenium.BuildCli</PackageId>
		<PackageTags>ingenium;build;git;submodule;cli</PackageTags>
		<Version>0.1.0</Version>
		<RollForward>LatestMajor</RollForward>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Spectre.Console" />
		<PackageReference Include="Spectre.Console.Cli" />
	</ItemGroup>

</Project>
